version: 2
project_name: claudeload

before:
  hooks:
    - go mod tidy

builds:
  - id: claudeload
    main: ./cmd/claudeload
    binary: claudeload
    env:
      - CGO_ENABLED=0
    goos:
      - linux
      - darwin
      - windows
    goarch:
      - amd64
      - arm64

archives:
  - id: claudeload
    builds:
      - claudeload
    name_template: "claudeload_{{ .Version }}_{{ .Os }}_{{ .Arch }}"
    format: tar.gz
    format_overrides:
      - goos: windows
        format: zip

checksum:
  name_template: "checksums.txt"

release:
  github:
    owner: LabGuy94
    name: claudeload
  draft: false
  prerelease: auto

changelog:
  sort: asc
  filters:
    exclude:
      - "^docs:"
      - "^test:"
